# Generated by Django 4.0.6 on 2022-07-28 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_ambientes', '0002_alter_ambiente_aforo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('generica', 'Genérica'), ('especifica', 'Específica')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_identificación', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería')], max_length=200)),
                ('identificación', models.CharField(max_length=64)),
                ('tipo_docente', models.CharField(choices=[('tecnico', 'Técnico'), ('profesional', 'Profesional')], max_length=200)),
                ('tipo_contrato', models.CharField(choices=[('PT', 'Planta'), ('CNT', 'Contratista')], max_length=200)),
                ('area', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('final', models.TimeField()),
                ('ambiente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_ambientes.ambiente')),
                ('competencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_horarios.competencia')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_horarios.docente')),
            ],
        ),
        migrations.AddField(
            model_name='competencia',
            name='programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_horarios.programa'),
        ),
    ]
