# Generated by Django 4.0.6 on 2022-07-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_horarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='final',
            new_name='hora_final',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='inicio',
        ),
        migrations.AddField(
            model_name='horario',
            name='dia',
            field=models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('MI', 'Miercoles'), ('J', 'Jueves'), ('V', 'Viernes')], default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='hora_inicio',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
