# Generated by Django 4.0.6 on 2022-07-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_horarios', '0002_rename_final_horario_hora_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='identificación',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
