# Generated by Django 4.0.6 on 2022-07-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_horarios', '0004_docente_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='username',
            field=models.CharField(default='none', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
