# Generated by Django 4.0.6 on 2022-07-27 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_periodos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='duracion',
        ),
    ]
