# Generated by Django 4.0.6 on 2022-07-28 03:50

from django.db import migrations, models
import gestion_periodos.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_periodos', '0002_remove_periodo_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='fecha_final',
            field=models.DateTimeField(),
        ),
    ]
