# Generated by Django 4.0.6 on 2022-07-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_periodos', '0003_alter_periodo_fecha_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='fecha_final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
