# Generated by Django 4.0.6 on 2022-07-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_periodos', '0004_alter_periodo_fecha_final_alter_periodo_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
