# Generated by Django 4.0.6 on 2022-07-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('virtual', 'Virtual'), ('presencial', 'Presencial')], max_length=200)),
                ('aforo', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=200)),
            ],
        ),
    ]
