# Generated by Django 4.0.6 on 2022-07-28 03:43

from django.db import migrations, models
import gestion_ambientes.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ambientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='aforo',
            field=models.IntegerField(validators=[gestion_ambientes.models.Ambiente.validate_positive]),
        ),
    ]
